API_KEY: "r8_CKqwyG8dE4hhef9F2QJytbNx7R3ZWW10i7wGq"
tokenizer: "NousResearch/Llama-2-7b-chat-hf"
embed_model: "BAAI/bge-small-en-v1.5"
llama_chat: 
replicate_config:
  model: "meta/llama-2-7b-chat:8e6975e5ed6174911a6ff3d60540dfd4844201974602551e10e9e87ab143d81e"
  temperature: 0.01
  additional_kwargs:
    top_p: 1
    max_new_tokens: 300